networks: 
  backend:
    driver: bridge
  otel:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root-pass
    networks: 
      - backend

  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - otel

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    networks:
      - otel

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
    networks:
      - otel

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./otel/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel

  http:
    image: goboilerplate
    build:
      context: .
      args:
        - BUILD_VERSION=dev
        - GITHUB_OAUTH=${GITHUB_OAUTH}
    ports:
      - 7723:7723
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_started
      mongo:
        condition: service_started
      redis:
        condition: service_started
    networks: 
      - backend
      - otel
