networks: 
  backend:
    driver: bridge
  otel:
    external:
      true

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root-pass
    networks: 
      - backend

  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend

  http:
    image: goboilerplate
    build:
      context: .
      args:
        - BUILD_VERSION=dev
        - GITHUB_OAUTH=${GITHUB_OAUTH}
    ports:
      - 7723:7723
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_started
      mongo:
        condition: service_started
      redis:
        condition: service_started
    networks: 
      - backend
      - otel
