version: '3.8'

networks: 
  backend:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=kurio
      - MYSQL_PASSWORD=supersecret
      - MYSQL_ROOT_PASSWORD=root-pass
    networks: 
      - backend

  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend
  
  api:
    image: goboilerplate
    build:
      context: .
      args:
        - BUILD_VERSION=dev
        - GITHUB_OAUTH=${GITHUB_OAUTH}
    ports:
      - 7723:7723
    env_file:
      - .env
    depends_on:
      - mysql
      - mongo
      - redis
    networks: 
      - backend
