name: Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go environment
      uses: actions/setup-go@v3.3.1
      with:
        go-version: 1.19.3 # optional

    - name: Set Timezone
      # You may pin to the exact commit or the version.
      # uses: szenius/set-timezone@d1416e74a9a643cbf6c711905741e73e3a0c26b8
      uses: szenius/set-timezone@v1.1
      with:
        # Desired timezone for Linux
        timezoneLinux: Asia/Jakarta # optional, default is UTC
        # Desired timezone for MacOS
        timezoneMacos: Asia/Jakarta # optional, default is GMT
        # Desired timezone for Windows
        timezoneWindows: Asia/Jakarta # optional, default is UTC

    - name: Install dependencies
      run: make prepare-dev

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

    - name: Scan file system vulnerabilities
      # You may pin to the exact commit or the version.
      # uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5
      uses: aquasecurity/trivy-action@0.8.0
      with:
        # Scan type to use for scanning vulnerability
        scan-type: fs # optional, default is image
        # exit code when vulnerabilities were found
        exit-code: 1 # optional
        # ignore unfixed vulnerabilities
        ignore-unfixed: true # optional, default is false
        # comma-separated list of vulnerability types (os,library)
        vuln-type: library # optional, default is os,library
        # severities of vulnerabilities to be displayed
        severity: MEDIUM,HIGH,CRITICAL # optional, default is UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
        # output format (table, json, template)
        format: table # optional, default is table
        # comma separated list of directories where traversal is skipped
        skip-dirs: '' # optional, default is 
        # comma separated list of files to be skipped
        skip-files: '' # optional, default is 
        # specify where the cache is stored
        cache-dir: '' # optional, default is 
        # timeout (default 5m0s)
        timeout: 5m0s # optional, default is 
        # comma-separated list of what security issues to detect
        security-checks: vuln # optional, default is 
